# Demo config file 
# You can follow this template to create your own config file
# Refer to the config files in the configs/ directory to see all the available options

checkpointing:
  run_name: "pico-decoder-medium-1"
  save_to_hf: true
  hf_checkpoint:
    repo_id: "pico-lm/pico-decoder-medium"

  learning_dynamics:
    batch_size: 128

model:
    d_model: 768
    activation_hidden_dim: 3072

monitoring:
  save_to_wandb: true
  wandb:
    project: "pico-decoder"
    entity: "pico-lm"

training:
  optimization:
    gradient_accumulation_steps: 8
  
  fabric:
    num_nodes: 4
    num_devices: 4
  
evaluation: 
  paloma:
    batch_size: 16
  